version: "3"

dotenv: [".env"]

interval: 500ms

tasks:
  g:synch:
    dotenv: [".env"]
    cmds:
      - go run cmd/main.go --config=$CONFIG_FILE__PATH {{ .CLI_ARGS }}
  generate:config:
    dotenv: [".env"]
    cmds:
      - touch $CONFIG_FILE__PATH
      - cp sample_config.yml $CONFIG_FILE__PATH
  test:
    dotenv: [".env"]
    cmds:
      - go test -v ./tests
  test:cover:
    dotenv: [".env"]
    cmds:
      - go test -v ./... -cover
