// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package pg_db

import (
	"context"
)

// iteratorForCreateTempRecords implements pgx.CopyFromSource.
type iteratorForCreateTempRecords struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTempRecords) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTempRecords) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForCreateTempRecords) Err() error {
	return nil
}

func (q *Queries) CreateTempRecords(ctx context.Context, id []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"compare_table"}, []string{"id"}, &iteratorForCreateTempRecords{rows: id})
}
