// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schema.sql

package pg_db

import (
	"context"
)

const loadSchema = `-- name: LoadSchema :exec
SELECT table_name
  FROM information_schema.tables
  WHERE table_schema = $1
ORDER BY table_name
`

func (q *Queries) LoadSchema(ctx context.Context, schemaName interface{}) error {
	_, err := q.db.Exec(ctx, loadSchema, schemaName)
	return err
}
