// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: table.sql

package pg_db

import (
	"context"
)

const getColumns = `-- name: GetColumns :exec
  SELECT
	     column_name,
	     data_type,
	     is_nullable,
	     column_default
	 FROM information_schema.columns
	 WHERE table_schema = $1 AND table_name = $2
	 ORDER BY ordinal_position
`

type GetColumnsParams struct {
	SchemaName interface{} `json:"schema_name"`
	TableName  interface{} `json:"table_name"`
}

func (q *Queries) GetColumns(ctx context.Context, arg GetColumnsParams) error {
	_, err := q.db.Exec(ctx, getColumns, arg.SchemaName, arg.TableName)
	return err
}

const getForeignKeys = `-- name: GetForeignKeys :exec
  SELECT
      kcu.column_name,
      ccu.table_name AS foreign_table_name,
      ccu.column_name AS foreign_column_name
  FROM
      information_schema.table_constraints AS tc
      JOIN information_schema.key_column_usage AS kcu
        ON tc.constraint_name = kcu.constraint_name
        AND tc.table_schema = kcu.table_schema
      JOIN information_schema.constraint_column_usage AS ccu
        ON ccu.constraint_name = tc.constraint_name
        AND ccu.table_schema = tc.table_schema
  WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_schema = $1 AND tc.table_name = $2
`

type GetForeignKeysParams struct {
	SchemaName interface{} `json:"schema_name"`
	TableName  interface{} `json:"table_name"`
}

func (q *Queries) GetForeignKeys(ctx context.Context, arg GetForeignKeysParams) error {
	_, err := q.db.Exec(ctx, getForeignKeys, arg.SchemaName, arg.TableName)
	return err
}

const getPrimaryKeys = `-- name: GetPrimaryKeys :exec
  SELECT
      kcu.column_name
  FROM
      information_schema.table_constraints AS tc
      JOIN information_schema.key_column_usage AS kcu
        ON tc.constraint_name = kcu.constraint_name
        AND tc.table_schema = kcu.table_schema
  WHERE tc.constraint_type = 'PRIMARY KEY' AND tc.table_schema = $1 AND tc.table_name = $2
  ORDER BY kcu.ordinal_position
`

type GetPrimaryKeysParams struct {
	SchemaName interface{} `json:"schema_name"`
	TableName  interface{} `json:"table_name"`
}

func (q *Queries) GetPrimaryKeys(ctx context.Context, arg GetPrimaryKeysParams) error {
	_, err := q.db.Exec(ctx, getPrimaryKeys, arg.SchemaName, arg.TableName)
	return err
}

const getTables = `-- name: GetTables :exec
  SELECT
      table_name
  FROM
      information_schema.tables
  WHERE table_schema = $1
`

func (q *Queries) GetTables(ctx context.Context, schemaName interface{}) error {
	_, err := q.db.Exec(ctx, getTables, schemaName)
	return err
}
