// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: temporary_tables.sql

package pg_db

import (
	"context"
)

const createTempCompareTable = `-- name: CreateTempCompareTable :exec
CREATE TEMP TABLE IF NOT EXISTS compare_table (
  id   TEXT PRIMARY KEY
)
`

func (q *Queries) CreateTempCompareTable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createTempCompareTable)
	return err
}

const truncateCompareTable = `-- name: TruncateCompareTable :exec
TRUNCATE TABLE compare_table
`

func (q *Queries) TruncateCompareTable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateCompareTable)
	return err
}
